umbraco/Umbraco.Deploy.Contrib

- src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors/MultiUrlPickerValueConnector.cs
Fixes an error which can occur on deployment when the datatype only allows selection of a single link (rather than allowing multiple links)
> Update to MultiUrlPicker to handle processing either single or multiple links

- README.md
- src/Umbraco.Deploy.Contrib.Connectors/Umbraco.Deploy.Contrib.Connectors.csproj
- src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors/NuPickersValueConnector.cs
Adds a value-connector for nuPickers.
The reason being is that nuPickers is flexible with the data it can handle, it is not limited to content or media nodes.
When associating nuPickers with the `GenericNodeIdPickerValueConnector` (in "Deploy.Settings.config"), this would strip out any non-node ID values.  Meaning that if nuPickers is being used to store "just string" values, those wouldn't be transferred to the target environment.
This custom value-connector will keep any non-node ID values intact, so they are transferred.
> nuPickers ValueConnector

- src/Umbraco.Deploy.Contrib.Connectors/GridCellValueConnectors/DocTypeGridEditorCellValueConnector.cs
Checks for a null in DTGE as doing .ToString() on a null throws
http://issues.umbraco.org/issue/deploy-467
> Fixes Deploy-467 - Checks for a null in DTGE

- src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors/InnerContentConnector.cs
If a value is detected as JSON, but isn't actually valid JSON, e.g. a string such as "[hello world]", then the `JToken.Parse` will throw an exception.
This patch introduces a `TryParse` style method to indicate whether the JToken conversion was successful, otherwise the value-connector can use the original (unmodified) value.
---
I took a cue from the [`ConvertToJsonIfPossible` extension method](https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Core/StringExtensions.cs#L158) in Umbraco core.
> InnerContentConnector - adds `TryParse` for the JToken conversion

- README.md
- src/Umbraco.Deploy.Contrib.Connectors/Umbraco.Deploy.Contrib.Connectors.csproj
- src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors/ContentListConnector.cs
We are preparing a release of a new property-editor called "[Content List](https://github.com/umco/umbraco-content-list)", and wanted to have Umbraco Cloud support upfront.
This is another "Inner Content" property-editor, so it re-uses the existing value-connector logic.
> Add value-connector for Content List

- README.md
- src/Umbraco.Deploy.Contrib.Connectors/Umbraco.Deploy.Contrib.Connectors.csproj
- src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors/TupleValueConnector.cs
- src/Umbraco.Deploy.Contrib.Tests/Connectors/TupleValueConnectorTests.cs
- src/Umbraco.Deploy.Contrib.Tests/Umbraco.Deploy.Contrib.Tests.csproj
We are preparing a release of a new property-editor called "[Tuple](https://github.com/umco/umbraco-tuple)", and wanted to have Umbraco Cloud support upfront.
I've included a unit-test too, (following the example from the Vorto unit-test).
> Add value-connector for Tuple

- .gitignore
- README.md
- src/Umbraco.Deploy.Contrib.Connectors/Umbraco.Deploy.Contrib.Connectors.csproj
- src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors/ArchetypeValueConnector.cs
- src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors/MeganavValueConnector.cs
- src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors/RelatedLinks2ValueConnector.cs
Although Cogworks has 'Umbraco Cloud / Courier' support listed as coming soon, I'm using this great property editor _right now_ on websites running on UC: https://github.com/thecogworks/meganav.  So I decided to write the connector myself and add it to this project (to keep additional assemblies to a minimum)... The connector itself is simple: replace id's with UDIs (and reverse on deploy) and track the dependencies.
I also ignored the Umbraco Deploy content files that are restored from NuGet and fixed 3 warnings (unused `ex` variable and 2 fields that should be properties).
> Cogworks.Meganav connector

- src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors/NuPickersValueConnector.cs
the string concat function was producing wrong xml, this change fixes it.
1. </Picker> was wrongly set as a parameter to string.Join resulting in the xml enumerable to return as a string
2. string.Join should not have a , separator as that would produce malformed xml
> Bugfix in SerializeValue when save format is XML

- src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors/NestedContentValueConnector.cs
When deploying nested content inside nested content, it would end up in a state where it was readable by the CMS - but not exactly saved in the correct format like the CMS would save it.
Data in this state would however fail to deploy via Deploy, which means that even though everything looks good after an initial deployment from one environment to another, any further deployments from that environment to another, would fail to transfer the data correctly.
While it didn't seem like a always-reproducible error .. it actually is. The cases where it did not seem to reproduce, was when a save had been done via the backoffice on the _deployed_ item before it was redeployed to the next environment. This would cause the CMS to "fix up" the format and then the item could be deployed to the next …
> AB-6447 - Nested content in nested content ends up in a semi corrupt format when deployed

- src/Umbraco.Deploy.Contrib.Connectors/Umbraco.Deploy.Contrib.Connectors.csproj
- src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors/BlockEditorValueConnector.cs
- src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors/BlockListValueConnector.cs
ValueConnector for transferring Block Editor based content. This will work with the Block List property editor for now.
Depending on where everything goes with the Block Editor based property editors, we may need to move functionality from the abstract connector if it turns out it will actually only apply to the Block List ValueConnector. 
- Create content using the Block List property editor, having references to both media and other content items.
- Ensure this content is transferred and that dependencies are transferred and handled correctly as well.
- (Further testing could include inspecting that the data is stored in the exact same format on both sides ... I've already done this though)
Currently there's a bug somewhere causing transfers of nested content inside nested content to …
> adding connector for blocklist property editor.

- src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors/BlockEditorValueConnector.cs
Update to use new JSON content schema from CMS core 8.7 for blocklist items
> Update to use new JSON content schema from CMS core 8.7

- src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors/BlockEditorValueConnector.cs
Makes the ToArtifact and FromArtifact virtual so that they can be overridden to allow for extra processing when used by custom block list editor prop editors that store additional info that would need more work performed on them
> Make ToArtifact/FromArtifact virtual

- src/Umbraco.Deploy.Contrib.Connectors/Properties/VersionInfo.cs
- src/Umbraco.Deploy.Contrib.Connectors/Umbraco.Deploy.Contrib.Connectors.csproj
- src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors/BlockEditorValueConnector.cs
- src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors/BlockListValueConnector.cs
- src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors/MultiUrlPickerValueConnector.cs
- src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors/NestedContentValueConnector.cs
- src/Umbraco.Deploy.Contrib.Tests/Properties/AssemblyInfo.cs
- src/Umbraco.Deploy.Contrib.Tests/TestHelpers/MockedMedia.cs
- src/Umbraco.Deploy.Contrib.Tests/Umbraco.Deploy.Contrib.Tests.csproj
Updated the code to depend on V9 of Deploy.
For review, a visual inspection is sufficient for now - further testing will be happening later on the different property editors covered here.  I've also taken a reference on a local NuGet package, which isn't yet up on a feed, so you won't actually be able to compile it locally.
Don't believe there's any points to flag - there's not much code and it all came over with just the usual updates needed (namespaces, logging, method signatures, dependencies).
> Updated to v9/net 5.

- src/Umbraco.Deploy.Contrib/ValueConnectors/BlockEditorValueConnector.cs
It's possible that a block editor value may have no settings collection, especially for 3rd party editors that don't need settings, so we need to null check before concatenating all nodes.
> Null check `blockEditorValue.Settings` before concatenating with `blockEditorValue.Content`

- src/Umbraco.Deploy.Contrib.Connectors/GridCellValueConnectors/DocTypeGridEditorCellValueConnector.cs
- src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors/NestedContentValueConnector.cs
This PR makes some changes to the `DocTypeGridEditorCellValueConnector` to handle when property editors such as nested content are used within it, as raised in [issue 82](https://github.com/umbraco/Umbraco.Deploy.Issues/issues/82).
The main change is to lean more on the dependent value connectors for the specific properties to parse the values rather than using parsing logic in the service connector.  Having done so this looks successfully and correctly transfer both simple properties such as text strings and RTEs, but also complex ones like nested content, multi-node tree picker and multi URL picker.
To Test:
- In test projects for Deploy, install [Doc Type Grid Editor](https://our.umbraco.com/packages/backoffice-extensions/doc-type-grid-editor/).
- Build the code from this PR and copy …
> Fixes DTGE connector to handle complex property editors such as nested content.

- src/Umbraco.Deploy.Contrib/ValueConnectors/BlockGridValueConnector.cs
This PR adds support for the new `Umbraco.BlockGrid` property editor that's added in https://github.com/umbraco/Umbraco-CMS/pull/12826 (part of the 10.3 release).
> Add support for `Umbraco.BlockGrid` property editor

- src/Umbraco.Deploy.Contrib.Connectors/GridCellValueConnectors/DocTypeGridEditorCellValueConnector.cs
- src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors/BlockEditorValueConnector.cs
- src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors/BlockListValueConnector.cs
- src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors/MultiUrlPickerValueConnector.cs
- src/Umbraco.Deploy.Contrib.Connectors/ValueConnectors/NestedContentValueConnector.cs
Continuing on PR https://github.com/umbraco/Umbraco.Deploy.Contrib/pull/54, this adds one additional cached entity key lookup in `MultiUrlPickerValueConnector`. Once the additional context cache helpers in Deploy (PR https://github.com/umbraco/Umbraco-Deploy/pull/701) are merged/released, we can bump the dependency version and also add caching to the `IMediaService.GetMediaByPath` and `IMediaService.GetById` calls 👍🏻
I've also added/updated the constructor null-checks to use throw expressions and removed the non-existent `Umbraco.BlockEditor` alias from the abstract `BlockEditorValueConnector` as mentioned in https://github.com/umbraco/Umbraco.Deploy.Contrib/pull/54#discussion_r953517991.
> Add additional caching using IContextCache

- src/Umbraco.Deploy.Contrib/Migrators/Legacy/DataType/PreValuesDataTypeArtifactJsonMigrator.cs
While testing a Deploy import from v7 using the legacy migrators, I noticed some data type pre-values/configuration values (for boolean values like `multiPicker`) had empty values, which causes the subsequent deserialization of the configuration object to fail.
This is fixed by skipping these empty values when pre-values are migrated to configuration in `PreValuesDataTypeArtifactJsonMigrator` 💪🏻
> Skip empty pre-values

- src/Umbraco.Deploy.Contrib/DataTypeConfigurationConnectors/DocTypeGridEditorDataTypeConfigurationConnector.cs
Although we already provide DocTypeGridEditor support for transferring content via the `DocTypeGridEditorCellValueConnector` (to parse nested values and add dependencies, including the used element types), it didn't properly support schema deployment for the Grid layout data type.
This PR adds a `DocTypeGridEditorDataTypeConfigurationConnector` that parses the Grid layout data type configuration and adds dependencies for any allowed element types for each DocTypeGridEditor grid editor. This ensures the element types are deployed first, before this data type is processed, which is required when doing a Grid layout to Block Grid migration (as that needs to know all element types when migrating the data type artifact)...
The easiest way to test is to copy over the added file into an Umbraco …
> Add DocTypeGridEditor data type configuration connector

- src/Umbraco.Deploy.Contrib/Migrators/ReplaceMatryoshkaArtifactMigrator.cs
This adds support for migrating Matryoshka Group Separators into native property groups by removing the Matryoshka data types during import and migrating the document, media and member types. Native property groups are also changed into tabs, similarly to how they were displayed with Matryoshka installed.
To test, add the following composer to a v13 project (it's probably the easiest to copy over the file in this PR into the Deploy test site) and import [export-TheStarterKit-Matryoshka.zip](https://github.com/user-attachments/files/16143567/export-TheStarterKit-Matryoshka.zip):
```c#
using Umbraco.Cms.Core.Composing;
using Umbraco.Deploy.Infrastructure.Migrators;
internal sealed class DeployMigratorsComposer : IComposer
{
public void Compose(IUmbracoBuilder builder)
{ …
```
> Add Matryoshka Group Separator artifact migrator

- Directory.Packages.props
- src/Umbraco.Deploy.Contrib/Migrators/DocTypeGridEditorPropertyTypeMigrator.cs
- src/Umbraco.Deploy.Contrib/Migrators/ReplaceDocTypeGridEditorDataTypeArtifactMigrator.cs
- src/Umbraco.Deploy.Contrib/packages.lock.json
- tests/Umbraco.Deploy.Contrib.Tests/packages.lock.json
This PR extends the built-in migrators (coming in Deploy 13.2.0) to migrate the legacy Grid layout using DocTypeGridEditor (exports need to be created using a version that contains PR https://github.com/umbraco/Umbraco.Deploy.Contrib/pull/65):
- `ReplaceDocTypeGridEditorDataTypeArtifactMigrator` extends `ReplaceGridDataTypeArtifactMigrator` and ensures any DocTypeGridEditor is migrated to blocks using the allowed element types (otherwise they will be migrated to new element types by the default implementation);
- `DocTypeGridEditorPropertyTypeMigrator` extends `GridPropertyTypeMigrator` and ensures the DocTypeGridEditor values are mapped 1:1 to the block item data.
I've created a Deploy 13.2.0-rc1 preview version on the MyGet pre-releases feed to test (and ensure this PR builds). Testing …
> Add migrators to support DocTypeGridEditor to Block Grid migration

- src/Umbraco.Deploy.Contrib/Extensions/ArtifactMigratorCollectionBuilderExtensions.cs
- src/Umbraco.Deploy.Contrib/Extensions/PropertyTypeMigratorCollectionBuilderExtensions.cs
- src/Umbraco.Deploy.Contrib/Migrators/Legacy/Content/CheckBoxListPropertyTypeMigrator.cs
- src/Umbraco.Deploy.Contrib/Migrators/Legacy/Content/CheckBoxListPropertyValueArtifactMigrator.cs
- src/Umbraco.Deploy.Contrib/Migrators/Legacy/Content/DropDownListFlexiblePropertyTypeMigrator.cs
- src/Umbraco.Deploy.Contrib/Migrators/Legacy/Content/DropDownListFlexiblePropertyValueArtifactMigrator.cs
- src/Umbraco.Deploy.Contrib/Migrators/Legacy/Content/DropDownMultiplePropertyTypeMigrator.cs
- src/Umbraco.Deploy.Contrib/Migrators/Legacy/Content/DropDownPropertyTypeMigrator.cs
- src/Umbraco.Deploy.Contrib/Migrators/Legacy/Content/DropdownlistMultiplePublishKeysPropertyTypeMigrator.cs
- src/Umbraco.Deploy.Contrib/Migrators/Legacy/Content/DropdownlistPublishingKeysPropertyTypeMigrator.cs
- src/Umbraco.Deploy.Contrib/Migrators/Legacy/Content/PrevalueArtifactMigrator.cs
- src/Umbraco.Deploy.Contrib/Migrators/Legacy/Content/PrevaluePropertyTypeMigratorBase.cs
- src/Umbraco.Deploy.Contrib/Migrators/Legacy/Content/PrevaluePropertyValueArtifactMigratorBase.cs
- src/Umbraco.Deploy.Contrib/Migrators/Legacy/Content/RadioButtonListPropertyTypeMigrator.cs
- src/Umbraco.Deploy.Contrib/Migrators/Legacy/Content/RadioButtonListPropertyValueArtifactMigrator.cs
Although PR https://github.com/umbraco/Umbraco.Deploy.Contrib/pull/61 added support for migrating pre-value property values, it used artifact migrators inherited from `PrevaluePropertyValueArtifactMigratorBase` (using Deploys `PropertyValueArtifactMigratorBase`) that only migrates first level properties on the content artifacts. This was used because property type migrators are only executed when a property editor alias changes, but the following property editor aliases from Umbraco 7 are still used and are therefore unchanged:
- `Umbraco.CheckBoxList`
- `Umbraco.DropDown.Flexible`
- `Umbraco.RadioButtonList`
However, if these property editors are used in nested/recursive property values (like Nested Content), the values weren't migrated from the `;;` delimited string to either the single …
> Migrate nested/recursive legacy pre-value property values
